CONTROLLER_HEART_BEAT_EXPIRATION = 30
WORKER_HEART_BEAT_INTERVAL = 15

LOGDIR = "."

# Model Constants
IGNORE_INDEX = -100
# IMAGE_TOKEN_INDEX = -200 
# IMAGE_TOKEN_INDEX = 128256
IMAGE_TOKEN_INDEX = 153713#153713 #152689 #151665
# DEFAULT_IMAGE_TOKEN = "<image>"
DEFAULT_IMAGE_TOKEN = "<sequence>"

DEFAULT_IMAGE_PATCH_TOKEN = "<im_patch>"
DEFAULT_IM_START_TOKEN = "<im_start>"
DEFAULT_IM_END_TOKEN = "<im_end>"
IMAGE_PLACEHOLDER = "<image-placeholder>"
